import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const assets = sqliteTable("assets", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  universe: text("universe").notNull().default("Sem universo"),
  kind: text("kind").notNull().default("Imagem"),
  subject: text("subject"),
  status: text("status").notNull().default("Pendente"),
  previousStatus: text("previous_status"),
  tags: text("tags").notNull().default("[]"),
  r2Key: text("r2_key").notNull(),
  originalName: text("original_name").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull().default(0),
  sha256: text("sha256"),
  semanticFamily: text("semantic_family"),
  useCount: integer("use_count").notNull().default(0),
  projectOrigin: text("project_origin"),
  scriptReference: text("script_reference"),
  visualReference: text("visual_reference"),
  sourceUrl: text("source_url"),
  operationalNote: text("operational_note"),
  qaStatus: text("qa_status").notNull().default("NAO_AVALIADO"),
  lastUsedAt: integer("last_used_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});


export const fastPushCandidates = sqliteTable("fast_push_candidates", {
  id: text("id").primaryKey(),
  operationId: text("operation_id").notNull().unique(),
  batchId: text("batch_id"),
  projectId: text("project_id"),
  itemId: text("item_id"),
  projectItemId: text("project_item_id"),
  projectLinkStatus: text("project_link_status"),
  materializationBatchId: text("materialization_batch_id"),
  materializationItemId: text("materialization_item_id"),
  materializationFileId: text("materialization_file_id"),
  supervisorCandidateId: text("supervisor_candidate_id"),
  linkedAt: integer("linked_at", { mode: "timestamp_ms" }),
  slot: text("slot"),
  targetName: text("target_name"),
  sourceUrl: text("source_url").notNull(),
  sourceType: text("source_type").notNull().default("WEB"),
  universe: text("universe"),
  subject: text("subject"),
  concept: text("concept"),
  visualReference: text("visual_reference"),
  scriptReference: text("script_reference"),
  scene: text("scene"),
  arc: text("arc"),
  episodeCandidate: text("episode_candidate"),
  compositionClass: text("composition_class"),
  tags: text("tags").notNull().default("[]"),
  usedFor: text("used_for"),
  priority: integer("priority").notNull().default(1),
  searchMetadata: text("search_metadata").notNull().default("{}"),
  status: text("status").notNull().default("INGESTING"),
  failureReason: text("failure_reason"),
  sha256: text("sha256"),
  r2Key: text("r2_key"),
  mimeType: text("mime_type"),
  sizeBytes: integer("size_bytes"),
  assetId: text("asset_id").references(() => assets.id),
  duplicateOfCandidateId: text("duplicate_of_candidate_id"),
  decisionSource: text("decision_source"),
  decisionNote: text("decision_note"),
  analyzedAt: integer("analyzed_at", { mode: "timestamp_ms" }),
  promotedAt: integer("promoted_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const requests = sqliteTable("requests", {
  id: text("id").primaryKey(),
  project: text("project").notNull(),
  rawItems: text("raw_items").notNull(),
  itemCount: integer("item_count").notNull().default(0),
  status: text("status").notNull().default("Validando"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const imports = sqliteTable("imports", {
  id: text("id").primaryKey(),
  fileName: text("file_name").notNull(),
  r2Key: text("r2_key").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  status: text("status").notNull().default("Recebido"),
  manifestText: text("manifest_text"),
  warnings: text("warnings").notNull().default("[]"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const assetUsage = sqliteTable("asset_usage", {
  id: text("id").primaryKey(),
  assetId: text("asset_id").notNull().references(() => assets.id),
  project: text("project").notNull(),
  block: text("block"),
  preset: text("preset"),
  slot: text("slot"),
  role: text("role"),
  scriptReference: text("script_reference"),
  note: text("note"),
  status: text("status").notNull().default("Registrado"),
  usedAt: integer("used_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const assetConsultations = sqliteTable("asset_consultations", {
  id: text("id").primaryKey(),
  assetId: text("asset_id").references(() => assets.id),
  concept: text("concept").notNull(),
  project: text("project"),
  query: text("query"),
  selected: integer("selected", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const semanticStockPolicies = sqliteTable("semantic_stock_policies", {
  id: text("id").primaryKey(),
  concept: text("concept").notNull(),
  universe: text("universe").notNull().default("Sem universo"),
  kind: text("kind").notNull().default("Todos"),
  minimum: integer("minimum").notNull().default(3),
  ideal: integer("ideal").notNull().default(5),
  maximum: integer("maximum").notNull().default(10),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const automaticProjects = sqliteTable("automatic_projects", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  status: text("status").notNull().default("WAITING_FILES"),
  projectDomain: text("project_domain").notNull().default("GENERAL"),
  queuePriority: integer("queue_priority").notNull().default(1),
  readyAt: integer("ready_at", { mode: "timestamp_ms" }),
  originalReadyAt: integer("original_ready_at", { mode: "timestamp_ms" }),
  lastAction: text("last_action"),
  automatic: integer("automatic", { mode: "boolean" }).notNull().default(true),
  libraryFirst: integer("library_first", { mode: "boolean" }).notNull().default(true),
  externalSearch: integer("external_search", { mode: "boolean" }).notNull().default(true),
  parallelMaterialization: integer("parallel_materialization", { mode: "boolean" }).notNull().default(true),
  automaticTechnicalQa: integer("automatic_technical_qa", { mode: "boolean" }).notNull().default(true),
  automaticZip: integer("automatic_zip", { mode: "boolean" }).notNull().default(true),
  deleteZipOnComplete: integer("delete_zip_on_complete", { mode: "boolean" }).notNull().default(true),
  circuitBreaker: integer("circuit_breaker", { mode: "boolean" }).notNull().default(true),
  activeVersion: integer("active_version").notNull().default(1),
  collectionBatchId: text("collection_batch_id"),
  zipR2Key: text("zip_r2_key"),
  zipFileName: text("zip_file_name"),
  zipSizeBytes: integer("zip_size_bytes"),
  productionRevision: integer("production_revision").notNull().default(1),
  productionZipRevision: integer("production_zip_revision").notNull().default(0),
  productionZipR2Key: text("production_zip_r2_key"),
  productionZipFileName: text("production_zip_file_name"),
  productionZipSizeBytes: integer("production_zip_size_bytes"),
  pipelineStatus: text("pipeline_status").notNull().default("AGUARDANDO"),
  nextAction: text("next_action"),
  supervisorExecutionId: text("supervisor_execution_id"),
  supervisorLeaseStartedAt: integer("supervisor_lease_started_at", { mode: "timestamp_ms" }),
  supervisorLastSeenAt: integer("supervisor_last_seen_at", { mode: "timestamp_ms" }),
  supervisorLeaseExpiresAt: integer("supervisor_lease_expires_at", { mode: "timestamp_ms" }),
  supervisorStatus: text("supervisor_status").notNull().default("LIVRE"),
  previousExecutionId: text("previous_execution_id"),
  abandonedAt: integer("abandoned_at", { mode: "timestamp_ms" }),
  resumeReason: text("resume_reason"),
  resumedAt: integer("resumed_at", { mode: "timestamp_ms" }),
  stateVersion: integer("state_version").notNull().default(1),
  activePlanId: text("active_plan_id"),
  totalItems: integer("total_items").notNull().default(0),
  approvedCount: integer("approved_count").notNull().default(0),
  frozenCount: integer("frozen_count").notNull().default(0),
  collectingCount: integer("collecting_count").notNull().default(0),
  materializingCount: integer("materializing_count").notNull().default(0),
  waitingQaCount: integer("waiting_qa_count").notNull().default(0),
  relinkCount: integer("relink_count").notNull().default(0),
  technicalCount: integer("technical_count").notNull().default(0),
  waitingSeedCount: integer("waiting_seed_count").notNull().default(0),
  failedCount: integer("failed_count").notNull().default(0),
  pendingCount: integer("pending_count").notNull().default(0),
  lastFrozenAt: integer("last_frozen_at", { mode: "timestamp_ms" }),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const automaticProjectFiles = sqliteTable("automatic_project_files", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  role: text("role").notNull(),
  version: integer("version").notNull().default(1),
  fileName: text("file_name").notNull(),
  r2Key: text("r2_key").notNull(),
  mimeType: text("mime_type").notNull().default("text/plain"),
  sizeBytes: integer("size_bytes").notNull().default(0),
  contentHash: text("content_hash"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const projectProductionAssets = sqliteTable("project_production_assets", {
  id: text("id").primaryKey(),
  operationId: text("operation_id").notNull().unique(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  kind: text("kind").notNull().default("THUMB"),
  name: text("name").notNull(),
  variant: text("variant"),
  agentOrigin: text("agent_origin"),
  note: text("note"),
  status: text("status").notNull().default("THUMB_CANDIDATE"),
  selected: integer("selected", { mode: "boolean" }).notNull().default(false),
  sourceType: text("source_type").notNull().default("WEB"),
  sourceUrl: text("source_url"),
  r2Key: text("r2_key").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull().default(0),
  sha256: text("sha256"),
  decisionSource: text("decision_source"),
  decisionNote: text("decision_note"),
  decidedAt: integer("decided_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const projectTitleCandidates = sqliteTable("project_title_candidates", {
  id: text("id").primaryKey(),
  operationId: text("operation_id").notNull().unique(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  text: text("text").notNull(),
  variant: text("variant"),
  agentOrigin: text("agent_origin"),
  note: text("note"),
  score: integer("score"),
  status: text("status").notNull().default("TITLE_CANDIDATE"),
  selected: integer("selected", { mode: "boolean" }).notNull().default(false),
  decisionSource: text("decision_source"),
  decisionNote: text("decision_note"),
  decidedAt: integer("decided_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const automaticProjectItems = sqliteTable("automatic_project_items", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  version: integer("version").notNull().default(1),
  itemKey: text("item_key").notNull(),
  targetFile: text("target_file"),
  term: text("term").notNull(),
  context: text("context"),
  kind: text("kind").notNull().default("contextual"),
  universe: text("universe"),
  itemDomain: text("item_domain"),
  stage: text("stage"),
  stageReadyAt: integer("stage_ready_at", { mode: "timestamp_ms" }),
  originalReadyAt: integer("original_ready_at", { mode: "timestamp_ms" }),
  notes: text("notes"),
  compositionClass: text("composition_class").notNull().default("CONTEXTUAL"),
  semanticClass: text("semantic_class"),
  familyId: text("family_id"),
  familySeedItemId: text("family_seed_item_id"),
  semanticReference: text("semantic_reference"),
  searchPlan: text("search_plan"),
  strategyState: text("strategy_state").notNull().default("{}"),
  requirementsHash: text("requirements_hash"),
  status: text("status").notNull().default("PARSING"),
  priority: integer("priority").notNull().default(1),
  sourceType: text("source_type"),
  linkedAssetId: text("linked_asset_id").references(() => assets.id),
  collectionTermId: text("collection_term_id"),
  collectionCandidateId: text("collection_candidate_id"),
  materializationBatchId: text("materialization_batch_id"),
  materializationItemId: text("materialization_item_id"),
  materializationFileId: text("materialization_file_id"),
  failureReason: text("failure_reason"),
  attempts: integer("attempts").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const automaticProjectEvents = sqliteTable("automatic_project_events", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  itemId: text("item_id"),
  event: text("event").notNull(),
  status: text("status"),
  detail: text("detail"),
  durationMs: integer("duration_ms"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const supervisorExecutions = sqliteTable("supervisor_executions", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  previousExecutionId: text("previous_execution_id"),
  status: text("status").notNull().default("ATIVO"),
  leaseStartedAt: integer("lease_started_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  leaseExpiresAt: integer("lease_expires_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  abandonedAt: integer("abandoned_at", { mode: "timestamp_ms" }),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  resumeReason: text("resume_reason"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const batches = sqliteTable("batches", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  project: text("project"),
  status: text("status").notNull().default("Rascunho"),
  manifestText: text("manifest_text"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const batchAssets = sqliteTable("batch_assets", {
  id: text("id").primaryKey(),
  batchId: text("batch_id").notNull().references(() => batches.id),
  assetId: text("asset_id").notNull().references(() => assets.id),
  position: integer("position").notNull().default(0),
  slot: text("slot"),
  note: text("note"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const mcpAudit = sqliteTable("mcp_audit", {
  id: text("id").primaryKey(),
  requestId: text("request_id"),
  tool: text("tool").notNull(),
  success: integer("success", { mode: "boolean" }).notNull().default(true),
  summary: text("summary"),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  finishedAt: integer("finished_at", { mode: "timestamp_ms" }),
  durationMs: integer("duration_ms"),
  authMs: integer("auth_ms").notNull().default(0),
  parseMs: integer("parse_ms").notNull().default(0),
  dbMs: integer("db_ms").notNull().default(0),
  dbQueryCount: integer("db_query_count").notNull().default(0),
  r2Ms: integer("r2_ms").notNull().default(0),
  r2RequestCount: integer("r2_request_count").notNull().default(0),
  externalHttpMs: integer("external_http_ms").notNull().default(0),
  externalHttpCount: integer("external_http_count").notNull().default(0),
  serializationMs: integer("serialization_ms").notNull().default(0),
  queueMs: integer("queue_ms").notNull().default(0),
  responseBytes: integer("response_bytes").notNull().default(0),
  rowsRead: integer("rows_read").notNull().default(0),
  rowsWritten: integer("rows_written").notNull().default(0),
  cacheHit: integer("cache_hit", { mode: "boolean" }).notNull().default(false),
  coldStart: integer("cold_start", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const operationResults = sqliteTable("operation_results", {
  operationId: text("operation_id").primaryKey(),
  tool: text("tool").notNull(),
  projectId: text("project_id"),
  status: text("status").notNull().default("RUNNING"),
  resultJson: text("result_json"),
  error: text("error"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const supervisorDecisionJobs = sqliteTable("supervisor_decision_jobs", {
  id: text("id").primaryKey(),
  operationId: text("operation_id").notNull().unique(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  kind: text("kind").notNull().default("PROJECT_QA"),
  status: text("status").notNull().default("QUEUED"),
  payloadJson: text("payload_json").notNull(),
  progressJson: text("progress_json").notNull().default("{}"),
  resultJson: text("result_json"),
  attempts: integer("attempts").notNull().default(0),
  leaseOwner: text("lease_owner"),
  leaseExpiresAt: integer("lease_expires_at", { mode: "timestamp_ms" }),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const sourceRouteMetrics = sqliteTable("source_route_metrics", {
  id: text("id").primaryKey(),
  universe: text("universe").notNull().default("*"),
  compositionClass: text("composition_class").notNull().default("*"),
  sourceId: text("source_id"),
  sourceName: text("source_name").notNull(),
  host: text("host").notNull().default("*"),
  attempts: integer("attempts").notNull().default(0),
  materialized: integer("materialized").notNull().default(0),
  approved: integer("approved").notNull().default(0),
  rejected: integer("rejected").notNull().default(0),
  technicalFailures: integer("technical_failures").notNull().default(0),
  semanticFailures: integer("semantic_failures").notNull().default(0),
  totalDurationMs: integer("total_duration_ms").notNull().default(0),
  score: integer("score").notNull().default(0),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const materializationBatches = sqliteTable("materialization_batches", {
  id: text("id").primaryKey(),
  project: text("project").notNull(),
  status: text("status").notNull().default("BATCH_CREATED"),
  totalItems: integer("total_items").notNull().default(0),
  completedItems: integer("completed_items").notNull().default(0),
  failedItems: integer("failed_items").notNull().default(0),
  cancelled: integer("cancelled", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const materializationItems = sqliteTable("materialization_items", {
  id: text("id").primaryKey(),
  batchId: text("batch_id").notNull(),
  itemId: text("item_id").notNull(),
  targetName: text("target_name").notNull(),
  concept: text("concept").notNull(),
  visualReference: text("visual_reference"),
  universe: text("universe"),
  preset: text("preset"),
  slot: text("slot"),
  kind: text("kind"),
  subject: text("subject"),
  tags: text("tags").notNull().default("[]"),
  scriptReference: text("script_reference"),
  usedFor: text("used_for"),
  minWidth: integer("min_width").notNull().default(64),
  minHeight: integer("min_height").notNull().default(64),
  requiresAlpha: integer("requires_alpha", { mode: "boolean" }).notNull().default(false),
  compositionClass: text("composition_class").notNull().default("CONTEXTUAL"),
  status: text("status").notNull().default("PENDING"),
  candidateCursor: integer("candidate_cursor").notNull().default(0),
  selectedCandidateId: text("selected_candidate_id"),
  selectedFileId: text("selected_file_id"),
  frozenAssetId: text("frozen_asset_id"),
  failureReason: text("failure_reason"),
  routeClass: text("route_class").notNull().default("MATERIALIZACAO_DIRETA"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const materializationCandidates = sqliteTable("materialization_candidates", {
  id: text("id").primaryKey(),
  itemDbId: text("item_db_id").notNull(),
  priority: integer("priority").notNull().default(1),
  source: text("source"),
  originalUrl: text("original_url").notNull(),
  resolvedUrl: text("resolved_url"),
  host: text("host"),
  adapter: text("adapter").notNull().default("generic"),
  status: text("status").notNull().default("PENDING"),
  failureReason: text("failure_reason"),
  attempts: integer("attempts").notNull().default(0),
  parentFileId: text("parent_file_id"),
  technicalOperation: text("technical_operation"),
  technicalParameters: text("technical_parameters"),
  httpStatus: integer("http_status"),
  contentType: text("content_type"),
  contentLength: integer("content_length"),
  redirectsCount: integer("redirects_count").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const materializationFiles = sqliteTable("materialization_files", {
  id: text("id").primaryKey(),
  itemDbId: text("item_db_id").notNull(),
  candidateId: text("candidate_id").notNull(),
  r2Key: text("r2_key").notNull(),
  mimeType: text("mime_type").notNull(),
  sizeBytes: integer("size_bytes").notNull(),
  width: integer("width"),
  height: integer("height"),
  sha256: text("sha256").notNull(),
  originalMimeType: text("original_mime_type"),
  originalSha256: text("original_sha256"),
  conversionType: text("conversion_type"),
  sourceFileId: text("source_file_id"),
  technicalOperation: text("technical_operation"),
  technicalParameters: text("technical_parameters"),
  technicalStatus: text("technical_status").notNull(),
  finalAssetId: text("final_asset_id"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const materializationHostHealth = sqliteTable("materialization_host_health", {
  host: text("host").primaryKey(),
  successCount: integer("success_count").notNull().default(0),
  failureCount: integer("failure_count").notNull().default(0),
  recentFailureCount: integer("recent_failure_count").notNull().default(0),
  circuitState: text("circuit_state").notNull().default("CLOSED"),
  blockedUntil: integer("blocked_until", { mode: "timestamp_ms" }),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const materializationHostProbes = sqliteTable("materialization_host_probes", {
  id: text("id").primaryKey(),
  urlHash: text("url_hash").notNull(),
  url: text("url").notNull(),
  host: text("host").notNull(),
  status: text("status").notNull(),
  httpStatus: integer("http_status"),
  contentType: text("content_type"),
  detail: text("detail"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const materializationLogs = sqliteTable("materialization_logs", {
  id: text("id").primaryKey(),
  batchId: text("batch_id"),
  itemDbId: text("item_db_id"),
  candidateId: text("candidate_id"),
  event: text("event").notNull(),
  status: text("status"),
  detail: text("detail"),
  durationMs: integer("duration_ms"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const collectionSources = sqliteTable("collection_sources", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  baseUrl: text("base_url").notNull(),
  method: text("method").notNull().default("GET"),
  queryParam: text("query_param").notNull().default("q"),
  limitParam: text("limit_param").notNull().default("limit"),
  imagePath: text("image_path").notNull(),
  thumbnailPath: text("thumbnail_path"),
  priority: integer("priority").notNull().default(3),
  active: integer("active", { mode: "boolean" }).notNull().default(true),
  apiKeyEnv: text("api_key_env"),
  apiKeyHeader: text("api_key_header"),
  headersJson: text("headers_json").notNull().default("{}"),
  userAgent: text("user_agent"),
  timeoutMs: integer("timeout_ms").notNull().default(25000),
  note: text("note"),
  domain: text("domain").notNull().default("MULTI"),
  supportedUniverses: text("supported_universes").notNull().default("[]"),
  supportedCompositionClasses: text("supported_composition_classes").notNull().default("[\"CONTEXTUAL\",\"ISOLATED\"]"),
  canDiscover: integer("can_discover", { mode: "boolean" }).notNull().default(true),
  canMaterialize: integer("can_materialize", { mode: "boolean" }).notNull().default(true),
  requiresExternalSearch: integer("requires_external_search", { mode: "boolean" }).notNull().default(false),
  configured: integer("configured", { mode: "boolean" }).notNull().default(true),
  capabilityVersion: integer("capability_version").notNull().default(1),
  queryCount: integer("query_count").notNull().default(0),
  foundCount: integer("found_count").notNull().default(0),
  uniqueCount: integer("unique_count").notNull().default(0),
  materializedCount: integer("materialized_count").notNull().default(0),
  failureCount: integer("failure_count").notNull().default(0),
  totalDurationMs: integer("total_duration_ms").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const collectionBatches = sqliteTable("collection_batches", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  status: text("status").notNull().default("CRIADO"),
  nightMode: integer("night_mode", { mode: "boolean" }).notNull().default(true),
  termsText: text("terms_text").notNull(),
  maxUrlsPerTerm: integer("max_urls_per_term").notNull().default(100),
  maxSourcesPerTerm: integer("max_sources_per_term").notNull().default(20),
  maxRoundsPerTerm: integer("max_rounds_per_term").notNull().default(5),
  maxTermMinutes: integer("max_term_minutes").notNull().default(45),
  maxTotalMinutes: integer("max_total_minutes").notNull().default(480),
  totalTerms: integer("total_terms").notNull().default(0),
  totalTarget: integer("total_target").notNull().default(0),
  totalCollected: integer("total_collected").notNull().default(0),
  reportText: text("report_text"),
  cancelled: integer("cancelled", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const collectionTerms = sqliteTable("collection_terms", {
  id: text("id").primaryKey(),
  batchId: text("batch_id").notNull().references(() => collectionBatches.id),
  term: text("term").notNull(),
  targetQuantity: integer("target_quantity").notNull(),
  kind: text("kind").notNull().default("qualquer"),
  universe: text("universe"),
  status: text("status").notNull().default("PENDENTE"),
  collectedCount: integer("collected_count").notNull().default(0),
  attempts: integer("attempts").notNull().default(0),
  rounds: integer("rounds").notNull().default(0),
  sourceCursor: integer("source_cursor").notNull().default(0),
  failureReason: text("failure_reason"),
  sourcePlan: text("source_plan"),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const collectionCandidates = sqliteTable("collection_candidates", {
  id: text("id").primaryKey(),
  batchId: text("batch_id").notNull().references(() => collectionBatches.id),
  termId: text("term_id").notNull().references(() => collectionTerms.id),
  sourceId: text("source_id").notNull().references(() => collectionSources.id),
  url: text("url").notNull(),
  normalizedUrl: text("normalized_url").notNull(),
  thumbnail: text("thumbnail"),
  estimatedType: text("estimated_type"),
  priority: integer("priority").notNull().default(1),
  status: text("status").notNull().default("CANDIDATA"),
  failureReason: text("failure_reason"),
  sha256: text("sha256"),
  materializationBatchId: text("materialization_batch_id"),
  materializationItemId: text("materialization_item_id"),
  materializationFileId: text("materialization_file_id"),
  assetId: text("asset_id"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const collectionSourceRuns = sqliteTable("collection_source_runs", {
  id: text("id").primaryKey(),
  batchId: text("batch_id").notNull(),
  termId: text("term_id").notNull(),
  sourceId: text("source_id").notNull(),
  foundCount: integer("found_count").notNull().default(0),
  uniqueCount: integer("unique_count").notNull().default(0),
  materializedCount: integer("materialized_count").notNull().default(0),
  failureCount: integer("failure_count").notNull().default(0),
  durationMs: integer("duration_ms").notNull().default(0),
  status: text("status").notNull(),
  detail: text("detail"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});


// Supervisor operacional via MCP (V45)
export const sourceProfiles = sqliteTable("source_profiles", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  status: text("status").notNull().default("ATIVO"),
  type: text("type").notNull().default("qualquer"),
  domain: text("domain").notNull().default("GENERAL"),
  universes: text("universes").notNull().default("[]"),
  compositionClass: text("composition_class"),
  semanticClass: text("semantic_class"),
  preferredHosts: text("preferred_hosts").notNull().default("[]"),
  blockedHosts: text("blocked_hosts").notNull().default("[]"),
  preferredSources: text("preferred_sources").notNull().default("[]"),
  queryTemplate: text("query_template"),
  negativeTerms: text("negative_terms").notNull().default("[]"),
  timeoutMs: integer("timeout_ms").notNull().default(5000),
  maxConsecutiveFailures: integer("max_consecutive_failures").notNull().default(2),
  maxUrlsPerTerm: integer("max_urls_per_term").notNull().default(60),
  maxSourcesPerTerm: integer("max_sources_per_term").notNull().default(20),
  maxRounds: integer("max_rounds").notNull().default(3),
  acceptedFormats: text("accepted_formats").notNull().default("[\"png\",\"webp\",\"jpg\",\"jpeg\"]"),
  materializationMode: text("materialization_mode").notNull().default("direta"),
  allowedConversions: text("allowed_conversions").notNull().default("[]"),
  transparency: text("transparency"),
  minWidth: integer("min_width").notNull().default(64),
  minHeight: integer("min_height").notNull().default(64),
  technicalSuccessRate: integer("technical_success_rate").notNull().default(0),
  visualApprovalRate: integer("visual_approval_rate").notNull().default(0),
  avgTimeMs: integer("avg_time_ms").notNull().default(0),
  technicalSuccesses: integer("technical_successes").notNull().default(0),
  technicalFailures: integer("technical_failures").notNull().default(0),
  visualApprovals: integer("visual_approvals").notNull().default(0),
  visualRejections: integer("visual_rejections").notNull().default(0),
  priority: integer("priority").notNull().default(3),
  isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false),
  notes: text("notes"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const supervisorProjectCandidates = sqliteTable("supervisor_project_candidates", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  itemId: text("item_id").notNull().references(() => automaticProjectItems.id),
  collectionCandidateId: text("collection_candidate_id"),
  materializationBatchId: text("materialization_batch_id").notNull(),
  materializationItemId: text("materialization_item_id").notNull(),
  materializationCandidateId: text("materialization_candidate_id"),
  materializationFileId: text("materialization_file_id").notNull(),
  source: text("source"),
  originalUrl: text("original_url"),
  host: text("host"),
  status: text("status").notNull().default("PARA_ANALISE"),
  metadata: text("metadata").notNull().default("{}"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const supervisorDecisionQueue = sqliteTable("supervisor_decision_queue", {
  id: text("id").primaryKey(),
  projectId: text("project_id").references(() => automaticProjects.id),
  itemId: text("item_id").references(() => automaticProjectItems.id),
  candidateId: text("candidate_id"),
  type: text("type").notNull(),
  priority: integer("priority").notNull().default(1),
  state: text("state").notNull().default("PENDENTE"),
  evidence: text("evidence").notNull().default("{}"),
  allowedActions: text("allowed_actions").notNull().default("[]"),
  decision: text("decision"),
  observation: text("observation"),
  source: text("source").notNull().default("AUTOMATICO"),
  resolvedAt: integer("resolved_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const supervisorConfigEvents = sqliteTable("supervisor_config_events", {
  id: text("id").primaryKey(),
  action: text("action").notNull(),
  key: text("key"),
  previousValue: text("previous_value"),
  nextValue: text("next_value"),
  source: text("source").notNull().default("SUPERVISOR_MCP"),
  reason: text("reason"),
  projectId: text("project_id"),
  itemId: text("item_id"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});


// Planejamento industrial do Supervisor (V60)
export const supervisorPlans = sqliteTable("supervisor_plans", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  executionId: text("execution_id"),
  operationId: text("operation_id"),
  idempotencyKey: text("idempotency_key"),
  status: text("status").notNull().default("ACCEPTED"),
  priority: integer("priority").notNull().default(1),
  intent: text("intent").notNull().default("EXECUTE_UNTIL_DIVERGENCE"),
  scopeJson: text("scope_json").notNull().default("{}"),
  maxParallelism: integer("max_parallelism").notNull().default(8),
  stopConditionsJson: text("stop_conditions_json").notNull().default("[]"),
  successConditionsJson: text("success_conditions_json").notNull().default("[]"),
  fallbackPolicyJson: text("fallback_policy_json").notNull().default("{}"),
  sourcePolicyJson: text("source_policy_json").notNull().default("{}"),
  qaPolicyJson: text("qa_policy_json").notNull().default("{}"),
  relinkPolicyJson: text("relink_policy_json").notNull().default("{}"),
  technicalPolicyJson: text("technical_policy_json").notNull().default("{}"),
  metadataJson: text("metadata_json").notNull().default("{}"),
  resultSummaryJson: text("result_summary_json").notNull().default("{}"),
  projectVersionAtCreation: integer("project_version_at_creation").notNull().default(1),
  policyVersion: text("policy_version").notNull().default("V60"),
  acceptedAt: integer("accepted_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const planBranches = sqliteTable("plan_branches", {
  id: text("id").primaryKey(),
  planId: text("plan_id").notNull().references(() => supervisorPlans.id),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  itemId: text("item_id").references(() => automaticProjectItems.id),
  stage: text("stage").notNull(),
  branchType: text("branch_type").notNull(),
  priority: integer("priority").notNull().default(1),
  status: text("status").notNull().default("READY"),
  readyAt: integer("ready_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  originalReadyAt: integer("original_ready_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  workerType: text("worker_type"),
  workerDomain: text("worker_domain").notNull().default("GENERAL"),
  leaseOwner: text("lease_owner"),
  leaseExecutionId: text("lease_execution_id"),
  leaseExpiresAt: integer("lease_expires_at", { mode: "timestamp_ms" }),
  attempt: integer("attempt").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  parentBranchId: text("parent_branch_id"),
  idempotencyKey: text("idempotency_key").notNull(),
  payloadJson: text("payload_json").notNull().default("{}"),
  resultJson: text("result_json").notNull().default("{}"),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  finishedAt: integer("finished_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const sourceRoutingPlans = sqliteTable("source_routing_plans", {
  id: text("id").primaryKey(),
  projectId: text("project_id").references(() => automaticProjects.id),
  itemId: text("item_id").references(() => automaticProjectItems.id),
  collectionTermId: text("collection_term_id"),
  projectDomain: text("project_domain").notNull().default("GENERAL"),
  universe: text("universe"),
  compositionClass: text("composition_class"),
  targetType: text("target_type"),
  canonicalReference: text("canonical_reference"),
  eligibleSourcesJson: text("eligible_sources_json").notNull().default("[]"),
  excludedSourcesJson: text("excluded_sources_json").notNull().default("[]"),
  discoverySourcesJson: text("discovery_sources_json").notNull().default("[]"),
  materializationSourcesJson: text("materialization_sources_json").notNull().default("[]"),
  fallbackSourcesJson: text("fallback_sources_json").notNull().default("[]"),
  routingVersion: integer("routing_version").notNull().default(1),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});


// Workspace de Políticas Operacionais / aprendizado industrial (V60+)
export const operationalGaps = sqliteTable("operational_gaps", {
  id: text("id").primaryKey(),
  signature: text("signature").notNull(),
  category: text("category").notNull(),
  severity: text("severity").notNull().default("MEDIUM"),
  projectId: text("project_id").references(() => automaticProjects.id),
  itemId: text("item_id").references(() => automaticProjectItems.id),
  domain: text("domain"),
  universe: text("universe"),
  compositionClass: text("composition_class"),
  semanticClass: text("semantic_class"),
  preset: text("preset"),
  source: text("source"),
  host: text("host"),
  tool: text("tool"),
  workerType: text("worker_type"),
  symptom: text("symptom").notNull(),
  rootCause: text("root_cause"),
  evidenceJson: text("evidence_json").notNull().default("{}"),
  occurrenceCount: integer("occurrence_count").notNull().default(1),
  status: text("status").notNull().default("OPEN"),
  resolutionPolicyId: text("resolution_policy_id"),
  firstSeenAt: integer("first_seen_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const operationalPolicies = sqliteTable("operational_policies", {
  id: text("id").primaryKey(),
  policyKey: text("policy_key").notNull(),
  name: text("name").notNull(),
  description: text("description"),
  category: text("category").notNull(),
  status: text("status").notNull().default("DRAFT"),
  ruleType: text("rule_type").notNull().default("LEARNED_POLICY"),
  scopeLevel: text("scope_level").notNull().default("PROJECT"),
  propagationLevel: integer("propagation_level").notNull().default(1),
  domain: text("domain"),
  universe: text("universe"),
  workType: text("work_type"),
  compositionClass: text("composition_class"),
  semanticClass: text("semantic_class"),
  preset: text("preset"),
  projectId: text("project_id").references(() => automaticProjects.id),
  itemId: text("item_id").references(() => automaticProjectItems.id),
  conditionJson: text("condition_json").notNull().default("{}"),
  actionJson: text("action_json").notNull().default("{}"),
  priority: integer("priority").notNull().default(1),
  confidence: integer("confidence").notNull().default(50),
  sourceGapId: text("source_gap_id"),
  createdBy: text("created_by").notNull().default("SUPERVISOR_MCP"),
  version: integer("version").notNull().default(1),
  previousVersionId: text("previous_version_id"),
  rollbackToVersion: integer("rollback_to_version"),
  timesMatched: integer("times_matched").notNull().default(0),
  timesApplied: integer("times_applied").notNull().default(0),
  successCount: integer("success_count").notNull().default(0),
  failureCount: integer("failure_count").notNull().default(0),
  avgTimeBeforeMs: integer("avg_time_before_ms").notNull().default(0),
  avgTimeAfterMs: integer("avg_time_after_ms").notNull().default(0),
  approvalRateBefore: integer("approval_rate_before").notNull().default(0),
  approvalRateAfter: integer("approval_rate_after").notNull().default(0),
  costBefore: integer("cost_before").notNull().default(0),
  costAfter: integer("cost_after").notNull().default(0),
  lastAppliedAt: integer("last_applied_at", { mode: "timestamp_ms" }),
  lastResult: text("last_result"),
  notes: text("notes"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const operationalPolicyEvents = sqliteTable("operational_policy_events", {
  id: text("id").primaryKey(),
  policyId: text("policy_id").references(() => operationalPolicies.id),
  policyVersion: integer("policy_version"),
  gapId: text("gap_id").references(() => operationalGaps.id),
  projectId: text("project_id").references(() => automaticProjects.id),
  itemId: text("item_id").references(() => automaticProjectItems.id),
  eventType: text("event_type").notNull(),
  beforeStateJson: text("before_state_json").notNull().default("{}"),
  afterStateJson: text("after_state_json").notNull().default("{}"),
  actionJson: text("action_json").notNull().default("{}"),
  result: text("result"),
  timeSavedMs: integer("time_saved_ms").notNull().default(0),
  requestsSaved: integer("requests_saved").notNull().default(0),
  externalRequestsSaved: integer("external_requests_saved").notNull().default(0),
  falsePositive: integer("false_positive", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

// Orquestração multi-worker / multi-nicho (V55)
export const workerCapacityLimits = sqliteTable("worker_capacity_limits", {
  id: text("id").primaryKey(),
  workerType: text("worker_type").notNull(),
  workerDomain: text("worker_domain").notNull().default("*"),
  maxWorkers: integer("max_workers").notNull().default(3),
  maxPerProject: integer("max_per_project").notNull().default(3),
  enabled: integer("enabled", { mode: "boolean" }).notNull().default(true),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const workerSessions = sqliteTable("worker_sessions", {
  id: text("id").primaryKey(),
  workerId: text("worker_id").notNull(),
  workerType: text("worker_type").notNull(),
  workerDomain: text("worker_domain").notNull(),
  allowedDomains: text("allowed_domains").notNull().default("[]"),
  executionId: text("execution_id").notNull(),
  status: text("status").notNull().default("ATIVO"),
  currentWorkItemId: text("current_work_item_id"),
  projectId: text("project_id").references(() => automaticProjects.id),
  stage: text("stage"),
  lastAction: text("last_action"),
  startedAt: integer("started_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  lastSeenAt: integer("last_seen_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  stoppedAt: integer("stopped_at", { mode: "timestamp_ms" }),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const workerWorkItems = sqliteTable("worker_work_items", {
  id: text("id").primaryKey(),
  scopeType: text("scope_type").notNull(),
  scopeId: text("scope_id").notNull(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  projectDomain: text("project_domain").notNull().default("GENERAL"),
  itemId: text("item_id").references(() => automaticProjectItems.id),
  stage: text("stage").notNull(),
  workerType: text("worker_type").notNull(),
  priority: integer("priority").notNull().default(1),
  resumePriority: integer("resume_priority").notNull().default(0),
  status: text("status").notNull().default("READY"),
  readyAt: integer("ready_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  originalReadyAt: integer("original_ready_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  attempts: integer("attempts").notNull().default(0),
  leaseOwnerWorkerId: text("lease_owner_worker_id"),
  leaseExecutionId: text("lease_execution_id"),
  leaseStartedAt: integer("lease_started_at", { mode: "timestamp_ms" }),
  leaseLastSeenAt: integer("lease_last_seen_at", { mode: "timestamp_ms" }),
  leaseExpiresAt: integer("lease_expires_at", { mode: "timestamp_ms" }),
  lastAction: text("last_action"),
  payloadJson: text("payload_json").notNull().default("{}"),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const workerEvents = sqliteTable("worker_events", {
  id: text("id").primaryKey(),
  workerId: text("worker_id"),
  workerType: text("worker_type"),
  workerDomain: text("worker_domain"),
  executionId: text("execution_id"),
  projectId: text("project_id").references(() => automaticProjects.id),
  workItemId: text("work_item_id"),
  stage: text("stage"),
  eventType: text("event_type").notNull(),
  status: text("status"),
  durationMs: integer("duration_ms"),
  metadataJson: text("metadata_json").notNull().default("{}"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const stageMetrics = sqliteTable("stage_metrics", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  projectDomain: text("project_domain").notNull().default("GENERAL"),
  workerId: text("worker_id"),
  workerType: text("worker_type"),
  workItemId: text("work_item_id"),
  stage: text("stage").notNull(),
  result: text("result").notNull(),
  durationMs: integer("duration_ms").notNull().default(0),
  queueWaitMs: integer("queue_wait_ms").notNull().default(0),
  attempts: integer("attempts").notNull().default(0),
  startedAt: integer("started_at", { mode: "timestamp_ms" }),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const queueSnapshots = sqliteTable("queue_snapshots", {
  id: text("id").primaryKey(),
  stage: text("stage").notNull(),
  projectDomain: text("project_domain").notNull(),
  readyCount: integer("ready_count").notNull().default(0),
  leasedCount: integer("leased_count").notNull().default(0),
  waitingCount: integer("waiting_count").notNull().default(0),
  capturedAt: integer("captured_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const projectRuns = sqliteTable("project_runs", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  projectDomain: text("project_domain").notNull().default("GENERAL"),
  status: text("status").notNull().default("ATIVO"),
  startedAt: integer("started_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  totalDurationMs: integer("total_duration_ms"),
  retries: integer("retries").notNull().default(0),
  relinks: integer("relinks").notNull().default(0),
  resumes: integer("resumes").notNull().default(0),
  workersInvolved: integer("workers_involved").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const exportJobs = sqliteTable("export_jobs", {
  id: text("id").primaryKey(),
  projectId: text("project_id").notNull().references(() => automaticProjects.id),
  projectDomain: text("project_domain").notNull().default("GENERAL"),
  status: text("status").notNull().default("READY"),
  assetSetHash: text("asset_set_hash"),
  r2Key: text("r2_key"),
  fileName: text("file_name"),
  sizeBytes: integer("size_bytes"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  completedAt: integer("completed_at", { mode: "timestamp_ms" }),
});
